# User config
author: "Timothy Dorn"
tagline: "Timothy Dorn's Portfolio"
description: "Please enjoy perusing my projects"
keywords: "Keywords"
email: "timothydorn1997@gmail.com"
resume: "https://drive.google.com/file/d/1U-0fPyps2sgKbNdxp-qpJKZsqDvSDCwj/view?usp=sharing"
linkedin: "https://www.linkedin.com/in/timothydorn/"
github: "https://github.com/TimothyDorn"


# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed